<?xml version="1.0" encoding="utf-8"?><Database Name="Shop" Class="ShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=D:\Study\AspNetDesignPattern\ASPPatterns.Chap3.SmartUI.Web\App_Data\Shop.mdf;Integrated Security=True" SettingsObjectName="ASPPatterns.Chap3.Layered.Repository.Properties.Settings" SettingsPropertyName="ShopConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Products">
    <Type Name="Product">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RRP" Type="System.Decimal" DbType="SmallMoney NOT NULL" CanBeNull="false" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="SmallMoney NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>